repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier . -w

  - repo: https://github.com/gitguardian/ggshield
    rev: v1.18.1
    hooks:
      - id: ggshield
        language_version: javascript
        stages: [commit]
