repos:
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: "v2.3.0"
      hooks:
          - id: prettier
            additional_dependencies:
                - "prettier@latest"
                - "@ianvs/prettier-plugin-sort-imports"
